### ISSUE TITLE
Schilder mit Layout aus eigenem Plugin verschwinden.

### ISSUE THREAD

**Issue by mineyannik** [zh32/TeleportSigns#1]
Hallo,

ich hoffe, dass du Deutsch verstehst.

Wenn ich in meinem Plugin die API benutzen möchte wird das Schild, welches mein Layout benutzt beim Neustart entfernt und das TeleportSigns Plugin scheint nicht zu starten.

Folgende Konsolenausgabe erhalte ich:
```
[19:34:53] [Server thread/INFO]: [TeleportSigns] Enabling TeleportSigns v1.3.2-b80
[19:34:53] [Server thread/ERROR]: [TeleportSigns] Deleting TeleportSign at Location{world=CraftWorld{name=world},x=1615.0,y=77.0,z=1083.0,pitch=0.0,yaw=0.0}
[19:34:53] [Server thread/ERROR]: Error occurred while enabling TeleportSigns v1.3.2-b80 (Is it up to date?)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_25]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_25]
	at de.zh32.teleportsigns.PluginData.checkSigns(PluginData.java:99) ~[?:?]
	at de.zh32.teleportsigns.PluginData.loadData(PluginData.java:56) ~[?:?]
	at de.zh32.teleportsigns.TeleportSigns.onEnable(TeleportSigns.java:34) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-eb39b47-0899683]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-eb39b47-0899683]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-eb39b47-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-eb39b47-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-eb39b47-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

Das ist mein Layout
```java
/*
 * Copyright Yannik Henke
 * www.mineyannik.de
 * All Rights reserved
 */
package de.mineyannik.semperlobby;

import de.zh32.teleportsigns.SignLayout;
import de.zh32.teleportsigns.ping.ServerInfo;
import org.bukkit.ChatColor;

/**
 *
 * @author yannikhenke
 */
public class SignLayouts implements SignLayout{

    @Override
    public boolean isTeleport() {
        return true;
    }

    @Override
    public String[] parseLayout(ServerInfo sinfo) {
        String[] temp = new String[4];
        if (sinfo.isOnline())
        {
            //Folgt
        }
        else
        {
            temp[0] = ChatColor.DARK_RED + "▉▉▉▉▉▉▉▉▉▉";
            temp[1] = ChatColor.DARK_RED + "[RESTARTING]";
            temp[2] = ChatColor.GRAY + sinfo.getDisplayname();
            temp[3] = ChatColor.DARK_RED + "▉▉▉▉▉▉▉▉▉▉";
        }
        return temp;
    }

    @Override
    public String getName() {
        return "sempercraft";
    }
    
}
```

Und so binde ich es ein:
```java
TeleportSigns.getInstance().addSignLayout(new SignLayouts());
```

**Comment by zh32** [comment]
Hi, ich arbeite gerade an einem Rewrite von TeleportSigns. Wenn ich bei der API für eigene Schilder ankomme, werde ich das hier beachten. Danke!

**Comment by TiTo-418** [comment]
@zh32 Status of this?
