### ISSUE TITLE
JSON Issue

### ISSUE THREAD

**Issue by Tigatok** [zh32/TeleportSigns#12]
This seems to be the outlying issue, not able to figure this out myself. Perhaps you can give some advice:

	public StatusResponse doStatusQuery() throws IOException {
		sendPacket(new byte[]{0x00});
		int size = readVarInt(connection.getDataInputStream());
		int packetId = readVarInt(connection.getDataInputStream());
		if (packetId != 0x00) {
			throw new IOException("Invalid packetId");
		}
		int stringLength = readVarInt(connection.getDataInputStream());
		if (stringLength < 1) {
			throw new IOException("Invalid string length.");
		}
		byte[] responseData = new byte[stringLength];
		connection.getDataInputStream().readFully(responseData);
		String jsonString = new String(responseData, Charset.forName("utf-8"));
		StatusResponse response = gson.fromJson(jsonString, StatusResponse.class);
		return response;
	}

[08:23:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin TeleportSigns v2.0-SNAPSHOT-b${BUILD_NUMBER} generated an exception while executing task 11
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at de.zh32.teleportsigns.server.status.QueryHandler.doStatusQuery(QueryHandler.java:47)
	at de.zh32.teleportsigns.server.status.ServerListPing.updateStatus(ServerListPing.java:29)
	at de.zh32.teleportsigns.task.ServerUpdateTask.execute(ServerUpdateTask.java:26)
	at de.zh32.teleportsigns.task.bukkit.BukkitServerUpdateTask.run(BukkitServerUpdateTask.java:22)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:821)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	... 13 more

**Comment by Tigatok** [comment]
Erm, no longer getting that exception any more. Not sure what happened... Maybe keep it on the back burner and see if something else could be causing it?

**Comment by zh32** [comment]
This is happening when gson tries to decode a response that is not in the format of StatusResponse.
