### ISSUE TITLE
JSON is not working

### ISSUE THREAD

**Issue by LoLCortex** [zh32/TeleportSigns#26]
[18:38:06 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17 path $.description
[18:38:06 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
[18:38:06 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
[18:38:06 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:852)
[18:38:06 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:801)
[18:38:06 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:773)
[18:38:06 WARN]:        at net.illusions.api.network.ServerPing.fetchData(ServerPing.java:134)
[18:38:06 WARN]:        at net.illusions.api.network.ServerInfoGetter.getPlayerCount(ServerInfoGetter.java:29)
[18:38:06 WARN]:        at net.illusions.api.network.signs.ServerSign.update(ServerSign.java:76)
[18:38:06 WARN]:        at net.illusions.api.network.signs.ServerSigns$1.run(ServerSigns.java:81)
[18:38:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[18:38:06 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[18:38:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[18:38:06 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[18:38:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[18:38:06 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[18:38:06 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:38:06 WARN]: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 17 path $.description
[18:38:06 WARN]:        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
[18:38:06 WARN]:        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
[18:38:06 WARN]:        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
[18:38:06 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
[18:38:06 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
[18:38:06 WARN]:        ... 15 more

This is the error log. Not sure what's happening here but it's your code, so I'll leave that up to you. Been reading online and was informed that this may not work after the 1.9 updates? Is this the case?

**Comment by montlikadani** [comment]
@LoLCortex 
This error should be reported here: https://github.com/google/gson/issues
