### ISSUE TITLE
NPE on ServerTeleporter.java:33 when clicking custom sign with [Shop] text on first line

### ISSUE THREAD

**Issue by Tigatok** [zh32/TeleportSigns#7]
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[hub.jar:git-Spigot-1a196e1-4ca1f89]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[hub.jar:git-Spigot-1a196e1-4ca1f89]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:840) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [hub.jar:git-Spigot-1a196e1-4ca1f89]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
	at de.zh32.teleportsigns.sign.ServerTeleporter.teleportPlayer(ServerTeleporter.java:33) ~[?:?]
	at de.zh32.teleportsigns.sign.BukkitServerTeleporter.onPlayerInteract(BukkitServerTeleporter.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[hub.jar:git-Spigot-1a196e1-4ca1f89]
	... 17 more

**Comment by zh32** [comment]
This should be fixed by #13.
